services:
  - type: web
    name: justspotify-backend
    runtime: docker
    buildCommand: "./mvnw clean package -DskipTests"
    startCommand: "java -Xmx512m -Dserver.port=$PORT -jar target/justspotify-0.0.1-SNAPSHOT.jar"
    healthCheckPath: /actuator/health
    autoDeploy: false
    plan: free
    buildFilter:
      ignoredPaths:
        - "*.md"
        - ".gitignore"
        - "*.log"
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: "prod"
      - key: SPRING_DATASOURCE_URL
        generateValue: true
      - key: SPRING_DATASOURCE_USERNAME
        generateValue: true
      - key: SPRING_DATASOURCE_PASSWORD
        generateValue: true
      - key: DROPBOX_ACCESS_TOKEN
        generateValue: true
      - key: MUSICPLATFORM_APP_JWTSECRET
        generateValue: true
      - key: MUSICPLATFORM_APP_JWTEXPIRATIONMS
        value: "86400000"
      - key: SPRING_MAIL_HOST
        value: "smtp.gmail.com"
      - key: SPRING_MAIL_PORT
        value: "587"
      - key: SPRING_MAIL_USERNAME
        generateValue: true
      - key: SPRING_MAIL_PASSWORD
        generateValue: true
      - key: SPRING_MAIL_PROPERTIES_MAIL_SMTP_AUTH
        value: "true"
      - key: SPRING_MAIL_PROPERTIES_MAIL_SMTP_STARTTLS_ENABLE
        value: "true"
      - key: APP_CORS_ALLOWED_ORIGINS
        generateValue: true